import java.io.IOException;
import java.util.*;

public class NewTask extends javax.swing.JFrame {
    private ArrayList<Task> tasks;
    private MainWindow main;
    private HashMap<String, ArrayList<Task>> groups;
    /**
     * Creates new form NewTask
     */
    public NewTask() {
        initComponents();
        tasks = new ArrayList<Task>();
    }
    
    //this constructor is called when the NewTask Window is created in the Main Window
    public NewTask(MainWindow main) throws IOException {
        initComponents();
        this.main = main;
        //tasks = new ArrayList<Task>();
        tasks = main.getTasks();
        groups = main.getGroups();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jTextField_task = new javax.swing.JTextField();
        jLabel_task = new javax.swing.JLabel();
        jComboBox_groups = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel_examples = new javax.swing.JLabel();
        jLabel_description = new javax.swing.JLabel();
        jTextField_description = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jLabel_confirm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel_title.setText("Adding a Task");

        jTextField_task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_taskActionPerformed(evt);
            }
        });

        jLabel_task.setText("Task Name:");

        jComboBox_groups.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add task to group" }));
        jComboBox_groups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_groupsActionPerformed(evt);
            }
        });

        jLabel3.setText("Add a description:");

        jLabel_name.setText("Descprition Name:");

        jLabel_examples.setText("(examples: date, location, etc)");

        jLabel_description.setText("Description:");

        jButton_add.setText("Add Task");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_title)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_task)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_task, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_groups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_name)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_examples))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_description)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_add)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_task, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_task))
                .addGap(18, 18, 18)
                .addComponent(jComboBox_groups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_examples))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_description)
                    .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_confirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_add))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //returns tasks
    public ArrayList<Task> getTasks() {
        return tasks;
    }
//    public HashMap<String, ArrayList<Task>> getGroups() {
//        return groups;
//    }
    
    //creates a new Task Object and adds that to the taskList and also the list of its respective group
    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        //confirms the task has been added
        jLabel_confirm.setText("" + jTextField_task.getText() + " added!");
        if (jTextField_name.getText().equals(""))
            tasks.add(new Task(jTextField_task.getText()));
        else if (jTextField_description.getText().equals(""))
            tasks.add(new Task(jTextField_task.getText(), jTextField_name.getText()));
        else
            tasks.add(new Task(jTextField_task.getText(), jTextField_name.getText(), jTextField_description.getText()));
        String group = (String) jComboBox_groups.getSelectedItem();
        for (String s : groups.keySet()) {
            if (group.equals(s)) {
                //adds task to group if necessary
                groups.get(s).add(tasks.get(tasks.size() - 1));
            }
        }
        //resets the fields
        jTextField_task.setText("");
        jTextField_name.setText("");
        jTextField_description.setText("");

    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTextField_taskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_taskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_taskActionPerformed

    private void jComboBox_groupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_groupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_groupsActionPerformed

    //fills up the combobox to show what groups you can add tasks into
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (String s : groups.keySet()) {
            jComboBox_groups.addItem(s);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JComboBox<String> jComboBox_groups;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_confirm;
    private javax.swing.JLabel jLabel_description;
    private javax.swing.JLabel jLabel_examples;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_task;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JTextField jTextField_description;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_task;
    // End of variables declaration//GEN-END:variables
}
